### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by Zmoonzxz** [LeapLabTHU/FLatten-Transformer#1]
Will you provide any other pretrained weights?

**Comment by tian-qing001** [comment]
Hi @Zmoonzxz , we provide the additional pretrained weights for FLatten-Swin-S/B/B-384, as you asked.
https://github.com/LeapLabTHU/FLatten-Transformer#pretrained-models

**Comment by Zmoonzxz** [comment]
> Hi @Zmoonzxz , we provide the additional pretrained weights for FLatten-Swin-S/B/B-384, as you asked. https://github.com/LeapLabTHU/FLatten-Transformer#pretrained-models

thanks a lot
