### ISSUE TITLE
关于可视化的一些问题

### ISSUE THREAD

**Issue by GloamXun** [LeapLabTHU/FLatten-Transformer#10]
论文中出现的DeiT-tiny的Attention Map的可视化是如何完成的，想问一下有没有相关的代码可以参考一下，感谢
![1](https://github.com/LeapLabTHU/FLatten-Transformer/assets/31510297/c441aded-334b-4b68-b82f-aad52825262d)

**Comment by tian-qing001** [comment]
Hi @GloamXun, we provide the code for visualization right [here](https://github.com/LeapLabTHU/FLatten-Transformer#visualization). You can use the `get_attn_matrix` function to obtain the attention map. Hoping that it could address your needs.
