### ISSUE TITLE
typical implementation form？

### ISSUE THREAD

**Issue by Rosal-1998** [LeapLabTHU/FLatten-Transformer#11]
I am attempting to reproduce your theory on a general attention mechanism, specifically by replacing softmax with flatten. However, I am having difficulty understanding the improvements made in Swin Transformer (SwinT) and Pyramid Vision Transformer (PVT). Can you provide a common implementation form.
thanks a lot!

**Comment by tian-qing001** [comment]
Hi @Rosal-1998, just replace the `Attention` module in your model with [FocusedLinearAttention](https://github.com/LeapLabTHU/FLatten-Transformer/blob/a02519f2ea97ea0973f4983130c4b4ae435ae7e6/models/flatten_swin.py#L164).
