### ISSUE TITLE
Request for DeiT-Tiny model definition.

### ISSUE THREAD

**Issue by hankyul2** [LeapLabTHU/FLatten-Transformer#12]
Hi @tian-qing001 

First, thank you for sharing your wonderful work as an open source. I appreciate your work.

**Question**: Can you share the flatten transformer implementation applied on the DeiT-T model? 

I am trying to reproduce [table 3 of the paper](https://arxiv.org/pdf/2308.00442.pdf) (shown in the below figure). If you could provide the implementation of your method on DeiT-T, it would help me a lot.
![image](https://github.com/LeapLabTHU/FLatten-Transformer/assets/31476895/482b45f9-caca-4ec9-b6f3-dd5aead165ba)

Thank you.

Hankyul.

**Comment by tian-qing001** [comment]
Hi @hankyul2, we sincerely appreciate your attention to our work. To access the script for the FLatten-DeiT-T model, please refer to [this resource](https://drive.google.com/file/d/1tf4pD6VQlq2uTzuPHjzE1b8I5XU8mwsZ/view?usp=share_link). It is worth pointing out that FLatten-DeiT-T was initially trained using a different code base. We plan to integrate it into this repository in the near future.

**Comment by hankyul2** [comment]
Thank you for your quick reply. It helps me to grasp how to implement your method on the DeiT-T model.

Thank you. 

Hankyul.

**Comment by Sahardastani** [comment]
Hi thank you for your excellent work. Can you please share your num_heads and embedding dimension for deit experiments? Is it similar to Inline_deit? 

Thank you
