### ISSUE TITLE
使用softplus对ReLU(query)进行缩放

### ISSUE THREAD

**Issue by YuhangGu4** [LeapLabTHU/FLatten-Transformer#14]
models.flatten_pvt.py文件中的124-129行代码：
kernel_function = nn.ReLU()
scale = nn.Softplus()(self.scale)
q = kernel_function(q) + 1e-6
k = kernel_function(k) + 1e-6
q = q / scale
k = k / scale
您好，我对您的研究成果非常感兴趣。可以给我解释一下，您为什么要在ReLU(query)之后使用softplus进行缩放么，谢谢。

**Comment by tian-qing001** [comment]
Hi @YuhangGu4, we use Softplus to ensure the non-negativity of `scale`. We did not use Softplus for query and key.

**Comment by YuhangGu4** [comment]
了解了，谢谢您的答复。
