### ISSUE TITLE
There is an error in the flatten_pvt.py file code  

### ISSUE THREAD

**Issue by qescccczmr** [LeapLabTHU/FLatten-Transformer#17]
![image](https://github.com/LeapLabTHU/FLatten-Transformer/assets/105876751/200f3da5-ade5-414f-a8f5-b90b6e93f524)
fix patch_embed1 which was wrong

**Comment by tian-qing001** [comment]
Hi, @qescccczmr. The [_get_pos_embed](https://github.com/LeapLabTHU/FLatten-Transformer/blob/20298dd598cec77170b2394b1b2194356280000c/models/flatten_pvt.py#L295C9-L295C23) function in our code is exactly the same as it in [PVT code](https://github.com/whai362/PVT/blob/57e2dfaa5a46f9050d76f306a4fcd9a7c061f520/classification/pvt.py#L201C5-L201C5).
