### ISSUE TITLE
分割数据集组织形式是什么？

### ISSUE THREAD

**Issue by renxiaosa00** [LeapLabTHU/FLatten-Transformer#2]
作者您好，非常荣幸看到您的文章，并且还加入数学公式的解释，以前我看到的文章多数都没写数学公式和实际添加模块的对应关系，所以看到您的文章，让我学到很多。我看文章的测试数据中有分类数据集的组织形式，它是不同文件夹代表不同类，但是分割数据集的形式是什么样子的呢？

**Comment by tian-qing001** [comment]
Hi @renxiaosa00, we sincerely appreciate your attention to and acknowledgment of our work. We conducted semantic segmentation experiments using the Swin Transformer's code on the standard ADE20K dataset. To delve into the details and initiate your own experiments, I recommend checking out  [mmsegmentation-ade20k](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#ade20k) and [Swin-Semantic-Segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation) for comprehensive data preparation and experimentation guidelines.

非常感谢你对我们工作的关注和肯定。语义分割实验我们是基于Swin Transformer的代码在标准的ADE20K数据集上开展的。关于组织数据和进行实验，建议您查看[mmsegmentation-ade20k](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#ade20k)和[Swin-Semantic-Segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation)。

**Comment by renxiaosa00** [comment]
> Hi @renxiaosa00, we sincerely appreciate your attention to and acknowledgment of our work. We conducted semantic segmentation experiments using the Swin Transformer's code on the standard ADE20K dataset. To delve into the details and initiate your own experiments, I recommend checking out [mmsegmentation-ade20k](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#ade20k) and [Swin-Semantic-Segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation) for comprehensive data preparation and experimentation guidelines.
> 
> 非常感谢你对我们工作的关注和肯定。语义分割实验我们是基于Swin Transformer的代码在标准的ADE20K数据集上开展的。关于组织数据和进行实验，建议您查看[mmsegmentation-ade20k](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#ade20k)和[Swin-Semantic-Segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation)。

非常感谢您的回复！我是做岩石的，主要是标注的时候图片很大，所以把原图和掩膜文件都裁剪到256*256大小了，我看工程里面对于模型的调用确实跟mmsegmentation很相似，我想了解的是如果我的掩膜文件不是json格式了，那我需要怎么修改数据读写那块的数据，才能测试一下这个工程呢？我的QQ是1379289573
