### ISSUE TITLE
Subject: Inquiry About Lightweight Feature Extraction with Your Attention Mechanism

### ISSUE THREAD

**Issue by Zhangyuhaoo** [LeapLabTHU/FLatten-Transformer#25]
I hope this message finds you well. I recently read your impressive paper on [FLatten Transformer: Vision Transformer using Focused Linear Attention], and I must say I was truly amazed by your work.

I am currently working on a task related to feature point extraction and matching, and my focus is on developing lightweight models. I am particularly interested in whether it would be feasible to replace the standard self-attention mechanisms in backbone networks with the attention mechanism you proposed in your research.

I would be grateful for your insights or suggestions on this approach. I apologize for any inconvenience my inquiry might cause and look forward to your response.

Thank you very much, and best wishes.

**Comment by tian-qing001** [comment]
Hi @Zhangyuhaoo, thanks for your interest in our work.
Focused linear attention can be used as an effecient and effective alternative to the standard Softmax self-attention in various models. And there are already some works working on this. Maybe you can try our method in your model.
