### ISSUE TITLE
window size swin

### ISSUE THREAD

**Issue by magehrig** [LeapLabTHU/FLatten-Transformer#29]
Thanks for open sourcing your work.

Unless I am not mistaken, you have a swin window size of 14x14 on stage (res3 with 14x14 resolution) because you set the window size to 56 [here](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/cfgs/flatten_swin_s.yaml#L9) and just skip windowing if the window size is larger or equal the resolution [here](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/models/flatten_swin.py#L281-L284). Hence, you don't actually have any window attention in Swin. This is not consistent with table 14 in your appendix of your [paper](https://arxiv.org/pdf/2308.00442). Just wanted to let you know, not sure if that changes anything.

**Comment by tian-qing001** [comment]
Hi @magehrig, thanks for your attention to our work.

The swin window size is 7x7 in stage 3, as the window size set in [the config](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/cfgs/flatten_swin_s.yaml#L9) only controls the window size for linear attention blocks. In stages 3 and 4, the window size for the original shifted window attention is kept as 7x7 for the 224x224 input. This is achieved by [this line](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/models/flatten_swin.py#L469) and [the config](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/cfgs/flatten_swin_s.yaml#L11).

**Comment by mathias-gehrig-skydio** [comment]
perfect, makes sense. Thanks!

**Comment by magehrig** [comment]
I see. Thanks!
