### ISSUE TITLE
Question on code details

### ISSUE THREAD

**Issue by magehrig** [LeapLabTHU/FLatten-Transformer#30]
Hi again :)

I have two small questions on implementation details:

1. In this [part](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/models/flatten_swin.py#L219-L224), you normalize over the full dimension before splitting into head dims. I would have expected that you normalize over the head dim (i.e. reshape first with head dim + normalize over head dim). Is there a specific reason for your choice? Did you also try normalizing over the head dim?

2. Just a [few lines later](https://github.com/LeapLabTHU/FLatten-Transformer/blob/abdb115f5406c0e1b6864aad7fe998a3f424ae76/models/flatten_swin.py#L230-L232), you first perform the mean over the token dim for k (`z = 1 / (q @ k.mean(dim=-2, keepdim=True).transpose(-2, -1) + 1e-6)`) , then normalize `k` and `v` with `N**-0.5` (`kv = (k.transpose(-2, -1) * (N ** -0.5)) @ (v * (N ** -0.5))`) and then `x = q @ kv * z`. That's mathematically equivalent to
```Python
z = 1 / (q @ k.sum(dim=-2, keepdim=True).transpose(-2, -1) + 1e-6)
kv = k.transpose(-2, -1) @ v
x = q @ kv * z
```
Did you choose your implementation due to numerical concerns?

Thanks for your time!

**Comment by tian-qing001** [comment]
Hi @magehrig, thanks for your questions, haha~
1. Generally, normalizing over the head dim has a similar impact as our current implementation. We empirically find that the current implementation may yield slightly better results than reshaping first in certain models.
2. This implementation aims to avoid the numerical instability problem, as a direct ```sum``` can lead to ```inf``` when dealing with long input sequences.

**Comment by Haus226** [comment]
May I ask the reason behind the Softplus function after the kernel_function but before the normalization with focusing factor, which is provided as below:

```python
scale = nn.Softplus()(self.scale)
q = q / scale
k = k / scale
q_norm = q.norm(dim=-1, keepdim=True)
k_norm = k.norm(dim=-1, keepdim=True)
q = q ** focusing_factor
k = k ** focusing_factor
q = (q / q.norm(dim=-1, keepdim=True)) * q_norm
k = (k / k.norm(dim=-1, keepdim=True)) * k_norm
```

Is it also contributing to more stabilized numerical computation?

**Comment by tian-qing001** [comment]
Hi @Haus226, thanks for your attention to our work. The Softplus function is applied to the learnable ``self.scale`` to ensure its non-negativity. We did not use Softplus for Q and K after the kernel function.
