### ISSUE TITLE
您好，您的工作非常有意义和参考价值，我像用来嫁接到CNN特征提取网络中，用于P345特征图之后，做一注意力机制，请问您代码支持吗？非常期待你的回信！十分感谢

### ISSUE THREAD

**Issue by 1324039468** [LeapLabTHU/FLatten-Transformer#6]

**Comment by tian-qing001** [comment]
Certainly. Our module can serve as a plug-in module and be adopted on a variety of modern CNN and ViT architectures. To implement this, I would recommend referring to the `FocusedLinearAttention` module in [swin.py](https://github.com/LeapLabTHU/FLatten-Transformer/blob/master/models/flatten_swin.py) and integrating it into your CNN models as needed.

**Comment by CHN-001** [comment]
> Certainly. Our module can serve as a plug-in module and be adopted on a variety of modern CNN and ViT architectures. To implement this, I would recommend referring to the `FocusedLinearAttention` module in [swin.py](https://github.com/LeapLabTHU/FLatten-Transformer/blob/master/models/flatten_swin.py) and integrating it into your CNN models as needed.

Thank you for your help! I have already applied the FocusedLinearAttention proposed by your team in the field of agricultural computer vision, and I think your team's work is excellent! The video on Bilibili is also great!
