### ISSUE TITLE
can not download pretrained weight

### ISSUE THREAD

**Issue by BubblyYi** [LeapLabTHU/FLatten-Transformer#7]
Hi, 

thanks for the great job! I encountered an issue with inaccessible web pages while downloading pre training weights
![prob](https://github.com/LeapLabTHU/FLatten-Transformer/assets/10595758/8cebf926-ffcf-4e28-908e-6d02e7310178)
Best,
James

**Comment by huoxingdawang** [comment]
Hi,
I also encountered the same problem.

**Comment by tian-qing001** [comment]
Hi @BubblyYi @huoxingdawang, the download link has been successfully updated, and you should now be able to download the pretrained weights without any issues. Thank you for bringing this to our attention.
